name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # Klona repo
      - uses: actions/checkout@v3

      # Lista filer för felsökning
      - name: List files
        run: ls -la

      # Navigera till React-projektmappen
      - name: Change to react project directory
        run: cd react_portfolio_project && ls -la

      # Installera Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ändra till 18 (mer stabil för React)

      # Installera dependencies
      - name: Install dependencies
        run: cd react_portfolio_project && npm install

      # Bygg appen
      - name: Build
        run: cd react_portfolio_project && npm run build

      # Deploy till Azure Static Web Apps
      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ZEALOUS_MEADOW_05CA8CA03 }}
          action: "upload"
          app_location: "react_portfolio_project"
          app_build_command: "npm run build"
          output_location: "dist"
          skip_api_build: true